datasource:
  driverName: mysql
  dataSourceName: root:Ling@tcp(127.0.0.1:3306)/douying?charset=utf8&interpolateParams=true
redis:
  host: localhost
  port: 6379
  password: Liang
server:
  port: 8080