// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFavorite = "tb_favorite"

// Favorite mapped from table <tb_favorite>
type Favorite struct {
	FavoriteID int64  `gorm:"column:favorite_id;primaryKey;autoIncrement:true" json:"favorite_id"`
	Username   string `gorm:"column:username" json:"username"`
	VideoID    int64  `gorm:"column:video_id" json:"video_id"`
	Isdeleted  int32  `gorm:"column:isdeleted" json:"isdeleted"`
}

// TableName Favorite's table name
func (*Favorite) TableName() string {
	return TableNameFavorite
}
