// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRelation = "tb_relation"

// Relation mapped from table <tb_relation>
type Relation struct {
	RelationID  int64 `gorm:"column:relation_id;primaryKey;autoIncrement:true" json:"relation_id"`
	FollowerID  int64 `gorm:"column:follower_id" json:"follower_id"`
	FollowingID int64 `gorm:"column:following_id" json:"following_id"`
	Isdeleted   int32 `gorm:"column:isdeleted" json:"isdeleted"`
}

// TableName Relation's table name
func (*Relation) TableName() string {
	return TableNameRelation
}
