// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "tb_user"

// User mapped from table <tb_user>
type User struct {
	UserID        int64  `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	Name          string `gorm:"column:name" json:"name"`
	FollowCount   int32  `gorm:"column:follow_count" json:"follow_count"`
	FollowerCount int32  `gorm:"column:follower_count" json:"follower_count"`
	IsFollow      int32  `gorm:"column:is_follow" json:"is_follow"`
	Password      string `gorm:"column:password" json:"password"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
