// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideo = "tb_video"

// Video mapped from table <tb_video>
type Video struct {
	VideoID       int64  `gorm:"column:video_id;primaryKey;autoIncrement:true" json:"video_id"`
	AuthorName    string `gorm:"column:author_name" json:"author_name"`
	PlayURL       string `gorm:"column:play_url" json:"play_url"`
	CoverURL      string `gorm:"column:cover_url" json:"cover_url"`
	FavoriteCount int32  `gorm:"column:favorite_count" json:"favorite_count"`
	CommentCount  int32  `gorm:"column:comment_count" json:"comment_count"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
